[package]
name = "remember"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libnotify = "1.0.3"
chrono = "0.4"
anyhow = "1.0.57"
